# nn.Module로 구현하는 선형 회귀

파이토치의 nn은 neural network(신경망)의 약자이다. 

nn에 정의되어 있는 nn.Linear() 함수와 평균제곱오차 nn.functional.mse_lose()라는 함수로 선형회귀 모델을 구현할 수 있다.

In [2]:
import torch.nn as nn
# model = nn.Linear(input_dim, output_dim)

In [3]:
import torch.nn.functional as F
# cost = F.mse_loss(prediction, y_train) # 손실 함수

## 단순 선형회귀(변수가 1개) 구현

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [7]:
model = nn.Linear(1,1) # input_dim, output_dim (뉴런의 수)

In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5878]], requires_grad=True), Parameter containing:
tensor([0.1183], requires_grad=True)]


nn.Linear를 통해 모델을 만들게 되면가중치가  **랜덤으로 초기화**된다. 이 값을 model.praameters()로 사용하여 불러올 수 있다.

첫번째 값이 W이고, 두번째 값이 b이다.

두 값 모두 학습 대상이므로(=반복적으로 수정되어야 하므로) requires_grad = True 인 것을 확인할 수 있다.

In [9]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) # 옵티마이저로 확률적 경사 하강법 사용, 학습률 지정.

In [10]:
nb_epochs = 2000
for epoch in range(1, nb_epochs + 1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad() # 그레디언트를 0으로 초기화
  cost.backward()

  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item() ))

Epoch  100/2000 Cost: 0.098756
Epoch  200/2000 Cost: 0.061025
Epoch  300/2000 Cost: 0.037710
Epoch  400/2000 Cost: 0.023302
Epoch  500/2000 Cost: 0.014399
Epoch  600/2000 Cost: 0.008898
Epoch  700/2000 Cost: 0.005498
Epoch  800/2000 Cost: 0.003398
Epoch  900/2000 Cost: 0.002100
Epoch 1000/2000 Cost: 0.001297
Epoch 1100/2000 Cost: 0.000802
Epoch 1200/2000 Cost: 0.000495
Epoch 1300/2000 Cost: 0.000306
Epoch 1400/2000 Cost: 0.000189
Epoch 1500/2000 Cost: 0.000117
Epoch 1600/2000 Cost: 0.000072
Epoch 1700/2000 Cost: 0.000045
Epoch 1800/2000 Cost: 0.000028
Epoch 1900/2000 Cost: 0.000017
Epoch 2000/2000 Cost: 0.000011


Cost가 작다 = 모델의 예측이 정답과 매우 유사하다

In [11]:
# 실제 모델 테스트

var = torch.FloatTensor([[4.0]])
pred_y = model(var)
print("모델에 4를 입력했을 때의 예측값 : ", pred_y)

모델에 4를 입력했을 때의 예측값 :  tensor([[7.9935]], grad_fn=<AddmmBackward0>)


이 모델의 정답은 Y = 2x이므로 정답에 근사한 값을 예측하고 있다.

In [12]:
# 학습 후의 모델 파라미터 값
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9962]], requires_grad=True), Parameter containing:
tensor([0.0085], requires_grad=True)]


"학습"한다는 것은 입력되는 변수에 곱해질 가중치를 찾는 과정이다. 

"학습된 모델"이라는 것은 찾아낸 가중치로 구한 **"함수"**이다.

모델 = 함수

함수를 구하면 어떠한 입력이 들어와도 출력을 계산할 수 있다. 

학습의 목적은 어떠한 입력이 들어와도 처리할 수 있는 모델을 만드는 것이다.

## 다중 선형 회귀(변수가 여러개)

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [14]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [15]:
model = nn.Linear(3,1)

In [16]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.0548, -0.5195,  0.3339]], requires_grad=True), Parameter containing:
tensor([0.4785], requires_grad=True)]


In [17]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [18]:
nb_epochs = 2000
for epoch in range(1, nb_epochs + 1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad() # 그레디언트를 0으로 초기화
  cost.backward()

  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item() ))

Epoch  100/2000 Cost: 1.143385
Epoch  200/2000 Cost: 1.118930
Epoch  300/2000 Cost: 1.095648
Epoch  400/2000 Cost: 1.073444
Epoch  500/2000 Cost: 1.052281
Epoch  600/2000 Cost: 1.032109
Epoch  700/2000 Cost: 1.012860
Epoch  800/2000 Cost: 0.994498
Epoch  900/2000 Cost: 0.976975
Epoch 1000/2000 Cost: 0.960260
Epoch 1100/2000 Cost: 0.944265
Epoch 1200/2000 Cost: 0.929005
Epoch 1300/2000 Cost: 0.914421
Epoch 1400/2000 Cost: 0.900468
Epoch 1500/2000 Cost: 0.887140
Epoch 1600/2000 Cost: 0.874383
Epoch 1700/2000 Cost: 0.862168
Epoch 1800/2000 Cost: 0.850479
Epoch 1900/2000 Cost: 0.839279
Epoch 2000/2000 Cost: 0.828548


In [19]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("입력이 73, 80, 75일 때의 예측값 :", pred_y) 

입력이 73, 80, 75일 때의 예측값 : tensor([[150.3520]], grad_fn=<AddmmBackward0>)


In [21]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7342, 0.2543, 1.0123]], requires_grad=True), Parameter containing:
tensor([0.4901], requires_grad=True)]


## 클래스로 파이토치 모델 구현하기

대부분 모델을 사용할 때는 클래스(Class)를 사용한다.

In [22]:
# model = nn.Linear(1,1)

In [27]:
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x):
    return self.linear(x)

In [28]:
model = LinearRegression()

위와 같은 모델 구현 형식은 대부분의 파이토치 구현체에서 사용하고 있는 방식이므로 반드시 숙지하도록 하자.

클래스(class) 형태의 모델은 nn.Module을 상속받는다. 

그리고 __ init __()에서 모델의 구조와 동작을 정의하는 생성자를 선언한다.

파이썬에서는 생성자에서 속성값을 초기화한다.(객체가 생성될 때 자동으로 호출)

super() 함수를 호출하면 nn.Module 클래스의 속성들을 가지고 초기화된다.

forward() 함수는 학습데이터를 입력받아 정방향 연산을 진행시키는 함수다. 이 함수는 모델이 객체를 **데이터와 함께 호출하면 자동으로 실행**이 된다.

### 단순 선형 회귀 클래스 구현 및 훈련

In [30]:
import torch
import torch.nn
import torch.nn.functional as F

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x): # 데이터와 함께 LinearRegression 호출하면 자동으로 실행됨
    return self.linear(x)

model = LinearRegression()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(1, nb_epochs + 1):

  prediction = model(x_train) # forward 자동으로 호출됨 -> 랜덤으로 파라미터 초기화됨

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad() # 그레디언트를 0으로 초기화
  cost.backward()

  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item() ))

Epoch  100/2000 Cost: 0.104637
Epoch  200/2000 Cost: 0.064659
Epoch  300/2000 Cost: 0.039955
Epoch  400/2000 Cost: 0.024690
Epoch  500/2000 Cost: 0.015257
Epoch  600/2000 Cost: 0.009428
Epoch  700/2000 Cost: 0.005826
Epoch  800/2000 Cost: 0.003600
Epoch  900/2000 Cost: 0.002225
Epoch 1000/2000 Cost: 0.001375
Epoch 1100/2000 Cost: 0.000849
Epoch 1200/2000 Cost: 0.000525
Epoch 1300/2000 Cost: 0.000324
Epoch 1400/2000 Cost: 0.000200
Epoch 1500/2000 Cost: 0.000124
Epoch 1600/2000 Cost: 0.000077
Epoch 1700/2000 Cost: 0.000047
Epoch 1800/2000 Cost: 0.000029
Epoch 1900/2000 Cost: 0.000018
Epoch 2000/2000 Cost: 0.000011


### 다중 선형 회귀 클래스 구현 및 훈련

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

class MultivariateLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

model = MultivariateLinearRegression()

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(1, nb_epochs + 1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad() # 그레디언트를 0으로 초기화
  cost.backward()

  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item() ))

Epoch  100/2000 Cost: 14.743709
Epoch  200/2000 Cost: 13.977470
Epoch  300/2000 Cost: 13.251581
Epoch  400/2000 Cost: 12.564047
Epoch  500/2000 Cost: 11.912766
Epoch  600/2000 Cost: 11.295761
Epoch  700/2000 Cost: 10.711370
Epoch  800/2000 Cost: 10.157763
Epoch  900/2000 Cost: 9.633334
Epoch 1000/2000 Cost: 9.136578
Epoch 1100/2000 Cost: 8.666019
Epoch 1200/2000 Cost: 8.220268
Epoch 1300/2000 Cost: 7.798032
Epoch 1400/2000 Cost: 7.398059
Epoch 1500/2000 Cost: 7.019191
Epoch 1600/2000 Cost: 6.660245
Epoch 1700/2000 Cost: 6.320267
Epoch 1800/2000 Cost: 5.998233
Epoch 1900/2000 Cost: 5.693156
Epoch 2000/2000 Cost: 5.404172
